name: monlmo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  syncfusion_flutter_charts: ^20.4.50
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/monlmo.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
